In [1]:
library(M4comp2018)
library(forecast)
library(dplyr)

Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo 


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union




In [2]:
Yearly_M4 <- Filter(function(l) l$period == "Yearly", M4)

In [3]:
data=Yearly_M4

In [4]:
data[[1]]

$st
[1] "Y1"

$x
Time Series:
Start = 1979 
End = 2009 
Frequency = 1 
 [1] 5172.1 5133.5 5186.9 5084.6 5182.0 5414.3 5576.2 5752.9 5955.2 6087.8
[11] 6238.9 6317.2 6262.7 6361.0 6427.4 6654.9 6835.4 6925.5 7073.5 7144.0
[21] 7230.6 7349.6 7339.2 7250.8 7294.6 7393.9 7560.9 7651.4 7587.3 7530.5
[31] 7261.1

$n
[1] 31

$type
[1] Macro
Levels: Demographic Finance Industry Macro Micro Other

$h
[1] 6

$period
[1] Yearly
Levels: Daily Hourly Monthly Quarterly Weekly Yearly

$xx
Time Series:
Start = 2010 
End = 2015 
Frequency = 1 
[1] 7290.2 7392.6 7527.6 7594.8 7720.7 7823.2

$pt_ff
          [,1]     [,2]     [,3]     [,4]     [,5]     [,6]
 [1,] 7243.994 7288.752 7333.678 7376.056 7423.142 7472.488
 [2,] 7291.322 7333.897 7376.682 7419.546 7462.400 7505.190
 [3,] 7172.993 7075.970 6997.268 6932.078 6876.902 6829.184
 [4,] 7253.999 7193.222 7142.116 7083.150 7032.515 7016.154
 [5,] 7192.472 7137.402 7092.809 7055.401 7022.899 6993.728
 [6,] 7198.113 7160.834 7142.344 7136.705 7139.811 7148.828
 [7,] 7206.992 7190.847 7187.583 7193.170 7204.810 7220.565
 [8,] 7307.464 7353.795 7400.127 7446.459 7492.791 7539.123
 [9,] 7240.417 7261.428 7282.501 7303.635 7324.830 7346.086
[10,] 7317.451 7373.549 7429.431 7485.102 7540.563 7595.818
[11,] 7322.897 7384.660 7446.424 7508.187 7569.951 7631.715
[12,] 7299.364 7236.854 7199.319 7179.131 7170.991 7171.219
[13,] 7322.237 7377.639 7430.921 7482.335 7532.091 7580.366
[14,] 7226.586 7163.285 7078.465 7015.925 6964.735 6885.627
[15,] 7167.547 6930.015 6764.461 6598.906 6433.352 7376.654
[16,] 7046.652 6832.154 6617.657 6403.159 6188.662 5974.164
[17,] 7262.600 7194.135 7123.547 7047.412 6972.735 6896.686
[18,] 7307.464 7353.795 7400.127 7446.459 7492.791 7539.123
[19,] 7130.701 7005.084 6890.054 6783.493 6683.707 6589.342
[20,] 7073.988 6944.030 6853.767 6791.075 6747.532 6717.289
[21,] 7489.245 7535.237 7581.229 7627.221 7673.214 7719.206
[22,] 7087.906 6929.107 6802.067 6700.436 6619.131 6554.087
[23,] 7095.570 6930.015 6764.461 6598.906 6433.352 6267.797
[24,] 7651.955 7712.596 7771.568 7828.919 7884.690 7938.914
[25,] 7291.814 7368.065 7497.866 7516.712 7535.064 7653.074

$up_ff
           [,1]      [,2]      [,3]      [,4]      [,5]      [,6]
 [1,]  7529.889  7656.278  7782.538  7930.319  8037.849  8201.059
 [2,]  7635.160  7922.878  8186.833  8430.985  8687.136  8842.622
 [3,]        NA        NA        NA        NA        NA        NA
 [4,]        NA        NA        NA        NA        NA        NA
 [5,]  7401.796  7482.598  7569.686  7677.730  7793.296  7870.152
 [6,]  7425.985  7524.885  7635.114  7733.309  7845.419  7947.263
 [7,]        NA        NA        NA        NA        NA        NA
 [8,]        NA        NA        NA        NA        NA        NA
 [9,]  7464.795  7694.940  7910.423  8111.862  8299.944  8475.400
[10,]        NA        NA        NA        NA        NA        NA
[11,]        NA        NA        NA        NA        NA        NA
[12,]  7523.691  7585.619  7671.546  7779.189  7882.078  8003.413
[13,]  7564.138  7709.147  7818.519  7914.499  8016.169  8249.956
[14,]        NA        NA        NA        NA        NA        NA
[15,]        NA        NA        NA        NA        NA        NA
[16,]        NA        NA        NA        NA        NA        NA
[17,]        NA        NA        NA        NA        NA        NA
[18,]        NA        NA        NA        NA        NA        NA
[19,]        NA        NA        NA        NA        NA        NA
[20,]  7268.489  7326.732  7424.507  7542.381  7669.191  7798.494
[21,]        NA        NA        NA        NA        NA        NA
[22,]        NA        NA        NA        NA        NA        NA
[23,]  7331.461  7368.799  7432.775  7523.005  7637.696  7775.139
[24,] 10237.791 10422.508 10602.407 10777.720 10948.648 11115.369
[25,]  8907.033 10165.892 11304.370 12305.488 12698.244 13692.653

$low_ff
          [,1]     [,2]     [,3]     [,4]     [,5]     [,6]
 [1,] 7033.413 6870.243 6720.930 6581.850 6437.012 6304.487


In [5]:
# pre_forecast_ets=function(data,freq,h,n,m,train_index)
# {
#     data_length=length(data)
#     pred = array(0,dim = c(data_length,n,m,6))
#     predh = array(0,dim = c(data_length,n,m,6))
#     train_time = numeric(data_length)
#     test_time = numeric(data_length)
#     for(k in 1:data_length){
#         start_time = Sys.time()
#         data=Yearly_M4
#         y = data[[k]]$x
#         y_pred = data[[k]]$xx
#         y_l=length(y)
#         loc = 1:length(y)
#         loc_n = as.integer(loc*n/length(y))
#         filt_d = data.frame(y,loc_n)
#         filt_0=filter(filt_d ,loc_n==0)
#         n_l=count(filt_0)
#         m_l=n_l/m
#         n_l=as.integer(n_l)
#         m_l=as.numeric(m_l)
#         for(i in 0:(n-1)){
#             for(j in 0:(m-1)){
#                 Y = ts(y[round((i*n_l+j*m_l)+1):y_l], end = end(y), frequency=freq)
#                 M = ets(Y) 
#                 pd=forecast(M, h=h)
#                 predh[k,(i+1),(j+1),] =pd$mean 
#                 pred[k,(i+1),(j+1),] = accuracy(pd, y_pred)[2,1:6]
#             }
#         }
#         end_time = Sys.time()
#         if (k %in% train_index) {
#             train_time[k] = end_time - start_time
#         } else {
#             test_time[k] = end_time - start_time
#         }
#     }
#     return(list(pred, predh, train_time, test_time))
# }

In [6]:
pre_forecast_ets=function(data,freq,h,m,n,train_index)
{
    data_length=length(data)
    pred = array(0,dim = c(data_length,m,n,6))
    predh = array(0,dim = c(data_length,m,n,h))
    train_matrix <- matrix(0,ncol = 3, nrow =data_length)
    test_matrix <- matrix(0,ncol = 3, nrow =data_length)
    colnames(train_matrix) <- c("user_time", "system_time", "elapsed_time")
    colnames(test_matrix) <- c("user_time", "system_time", "elapsed_time")
    for(k in 1:data_length){
        start_time = Sys.time()
        y = data[[k]]$x
        y_pred = data[[k]]$xx
        y_l=length(y)
        loc = 1:length(y)
        loc_m = as.integer(loc*m/length(y))
        filt_d = data.frame(y,loc_m)
        filt_0=filter(filt_d ,loc_m==0)
        m_l=count(filt_0)
        n_l=m_l/n
        m_l=as.integer(m_l)
        n_l=as.numeric(n_l)
        for(i in 0:(m-1)){
            for(j in 0:(n-1)){
                Y = ts(y[round((i*m_l+j*n_l)+1):y_l], end = end(y), frequency=freq)
                M = ets(Y) 
                pd=forecast(M, h=h)
                predh[k,(i+1),(j+1),] =pd$mean 
                pred[k,(i+1),(j+1),] = accuracy(pd, y_pred)[2,1:6]
            }
        }
        end_time = Sys.time()
        if (k %in% train_index) {
            train_matrix[k,] = end_time - start_time
        } else {
            test_matrix[k,] = end_time - start_time
        }
    }
    return(list(pred, predh, train_matrix, test_matrix))
}

In [7]:
set.seed(100)
index = sample(2,length(data),replace = TRUE,prob=c(0.7,0.3))
trainindex=c(1:length(data))[index==1]

In [8]:
head(trainindex)

[1] 1 2 3 4 5 6

In [ ]:
datalist=pre_forecast_ets(data,1,6,10,4,trainindex)

In [16]:
save(datalist, file = "year_ets_datalist.RData")

In [19]:
start_time = Sys.time()
pre_forecast_ets(data[1:50],1,6,5,4,trainindex)
end_time = Sys.time()
end_time - start_time

[[1]]
, , 1, 1

              [,1]        [,2]         [,3]         [,4]         [,5]
 [1,]   876.499807  1168.08398  1177.596089   297.056355   297.056376
 [2,]  -336.136559  -336.13653  -336.136505  -336.136556  -336.136556
 [3,]  -224.439856  -115.63380   -98.031882  -160.264409   441.682670
 [4,]  -482.398159  -348.02374  -429.413448  -277.932531   283.356360
 [5,]   469.645160   494.04033   -74.896020   302.766335   961.706723
 [6,] -2089.111477 -2090.66841 -2095.691847   171.308217   171.308134
 [7,] -3000.543183 -3006.30600  -356.362512  -356.362559  -356.362476
 [8,]   -47.044639    -7.22077   -17.105566   -18.788770   -12.225900
 [9,]  -402.325898  -434.15900   -63.461063   -63.461074   -63.461058
[10,]  -173.719618  -173.71960  -173.719576    22.784436    14.853172
[11,]    -6.743609   -10.76852   -27.719436   -27.719421   -27.719437
[12,]  -359.332960   -92.98246   -13.870089    31.925137    31.925136
[13,]  -233.950590  -350.13613  -355.187383   478.586428   478.586625
[14,]  -215.621534   -69.95293   244.599257   244.599215   244.599261
[15,]    -8.832052  -130.10155    -1.048004   525.025492   525.025504
[16,]   525.627178  -108.06808   525.625900   525.626504   367.451107
[17,]  -142.057709  -156.03300   223.535600   223.535599   223.535573
[18,]   123.177996   360.72712   377.238403   377.238327   301.550938
[19,]  -525.289373  -525.28934  -525.289240  -525.289016  -525.289266
[20,]   817.055674   817.05600   817.055578   817.055569   817.055585
[21,]  -593.091892  -593.09162  -593.091597  -593.091314  -593.091885
[22,]  -639.370455  -639.37020  -639.370398  -639.369569  -639.369805
[23,] -2458.314048 -2458.31483 -2458.314788 -2458.314722 -2458.314552
[24,] -1359.952323 -1359.95162 -1359.952012 -1359.949999 -1359.951021
[25,]     7.599534     7.59988     7.599690     7.599739     7.599849
[26,] -1476.340105 -1476.33904 -1476.340585 -1476.339001 -1476.340664
[27,]  -239.956038  -239.95591  -239.956071  -239.955746  -239.955944
[28,]  -316.315513  -316.31556  -316.315495  -316.315519  -316.315457
[29,]  -321.602637  -321.60231  -321.602720  -321.602710  -321.602717
[30,]  -298.093457  -313.01845  -304.870226     3.065896     3.065892
[31,]    71.181483   102.83526    85.142906    68.861838    73.774863
[32,] -1559.142616  -330.61023  -330.610146  -330.610130  -330.610144
[33,]  -116.482172  -133.91680  -107.206816   -71.931963   -71.932006
[34,]  -441.283761   -57.38440   -57.384399   -57.384377   -57.384412
[35,]  -122.750950  -145.63678  -145.131253  -162.494650  -162.494645
[36,]  -324.591028  -324.59105   -66.806978   -66.806981   -66.806981
[37,] -1526.759311 -1526.75940  -183.984627  -183.984509  -183.984628
[38,] 21438.836995 21389.94797 22481.806013 23349.512780  4386.623205
[39,]   885.682444   917.47904   879.691233   843.929137  1241.357041
[40,]   855.485727   398.85453   664.822646   139.951198    53.751073
[41,]  2047.307850  2234.21746   285.815179  2549.827915  2679.115619
[42,] -1026.482279 -1049.02957  -992.075023 -1140.491331 -1023.989665
[43,]  -321.594417  -304.66960  -313.491504  -329.680714  -297.320406
[44,]   156.741696   -41.88534   -68.299175   280.707552  -350.561416
[45,]   227.174459    25.81210   -32.220998   -45.579891  -242.878197
[46,]  -806.537929  -907.72836  -990.267615  -940.499342  -901.742009
[47,]  -976.264694 -1012.12702  -961.281345  -950.195787  -903.337855
[48,]  -890.435610 -1023.41987 -1023.413422 -1023.414105 -1329.982318
[49,]   -46.582361   -46.58236   -66.414849  -120.965220  -114.698012
[50,] -1097.682710  -499.74257  -454.346681  -682.666139  -424.143127

, , 2, 1

              [,1]         [,2]         [,3]         [,4]         [,5]
 [1,]  1117.638455  1133.630243   297.056390   297.056373   1103.66512
 [2,]  -336.136508  -336.136555  -336.136456  -336.136548  -1389.66667
 [3,]  -127.007750  -128.960215  -121.908845  -140.534604   -304.64254
 [4,]  -445.911434  -355.186237  -428.043367  -273.788571   -710.56689
 [5,]   494.440501   479.374991   112.126873   3

Time difference of 15.13747 secs